"""Replace notebook cells 41-44 (0-indexed 40-43) with RAGAS-inspired metrics."""
import json, uuid

NOTEBOOK = '13_IRTM_From_Text_to_Agentic_Training_Data_2025_2026.ipynb'

MD_10_5 = (
    "### 10.5  RAGAS-Inspired Evaluation Metrics\n"
    "\n"
    "The **RAGAS framework** (RAG Assessment) provides a principled set of metrics for evaluating RAG "
    "pipelines (slide deck *Measuring Quality*, pp.\u2009103\u2013112).  We apply five of them here to "
    "compare the **LLM baseline** with the **Agent** stage across both benchmarks:\n"
    "\n"
    "| Metric | Slides | What it measures |\n"
    "|---|---|---|\n"
    "| **Semantic Similarity** | p.\u2009105 | Cosine similarity of answer embedding vs reference embedding |\n"
    "| **Answer Relevancy** | p.\u2009106 | Cosine similarity of answer embedding vs question embedding |\n"
    "| **Context Relevancy** | p.\u2009107 | Fraction of retrieved context sentences that are relevant to the question |\n"
    "| **Faithfulness** | p.\u2009108 | Fraction of answer claims that can be inferred from the retrieved context |\n"
    "| **Answer Correctness** | p.\u2009109 | LLM-judged accuracy (1\u20135 scale, normalised to 0\u20131) |\n"
    "\n"
    "> **LLM-as-a-Judge** (p.\u2009112) is used in Section 10.6 for a pairwise comparison between the "
    "LLM baseline and the Agent stage.\n"
)

CODE_10_5 = (
    "# 10.5  RAGAS-Inspired Evaluation Metrics (Measuring Quality, pp. 103-112)\n"
    "\n"
    "import numpy as np\n"
    "\n"
    "# --- Embedding-based metrics (p. 105-106) --------------------------------\n"
    "\n"
    "def ragas_semantic_similarity(answer, reference):\n"
    "    \"\"\"Semantic Similarity (p.105): cosine similarity of answer vs reference embeddings.\"\"\"\n"
    "    if not answer or not reference or semantic_model is None:\n"
    "        return None\n"
    "    embs = semantic_model.encode([answer, reference], normalize_embeddings=True)\n"
    "    return round(float(np.dot(embs[0], embs[1])), 3)\n"
    "\n"
    "def ragas_answer_relevancy(question, answer):\n"
    "    \"\"\"Answer Relevancy (p.106): cosine similarity of answer vs question embeddings.\"\"\"\n"
    "    if not question or not answer or semantic_model is None:\n"
    "        return None\n"
    "    embs = semantic_model.encode([question, answer], normalize_embeddings=True)\n"
    "    return round(float(np.dot(embs[0], embs[1])), 3)\n"
    "\n"
    "# --- LLM-based metrics (p. 107-109) --------------------------------------\n"
    "\n"
    "def ragas_context_relevancy(question, context, max_ctx=800):\n"
    "    \"\"\"Context Relevancy (p.107): fraction of context sentences relevant to the question.\"\"\"\n"
    "    if not client or not context:\n"
    "        return None\n"
    "    prompt = (\n"
    "        f\"Question: {question}\\n\\n\"\n"
    "        f\"Context (excerpt):\\n{context[:max_ctx]}\\n\\n\"\n"
    "        \"Count the total number of sentences in the excerpt and how many are \"\n"
    "        \"relevant to answering the question. \"\n"
    "        'Return ONLY valid JSON: {\"total\": N, \"relevant\": M}'\n"
    "    )\n"
    "    try:\n"
    "        resp = client.chat.completions.create(\n"
    "            model=\"gpt-4o-mini\",\n"
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n"
    "            temperature=0, max_tokens=40,\n"
    "        )\n"
    "        data = json.loads(resp.choices[0].message.content.strip())\n"
    "        total = max(int(data.get(\"total\", 1)), 1)\n"
    "        return round(int(data.get(\"relevant\", 0)) / total, 3)\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "def ragas_faithfulness(answer, context, max_ctx=800):\n"
    "    \"\"\"Faithfulness (p.108): fraction of answer claims supported by the context.\"\"\"\n"
    "    if not client or not answer or not context:\n"
    "        return None\n"
    "    prompt = (\n"
    "        f\"Context:\\n{context[:max_ctx]}\\n\\n\"\n"
    "        f\"Answer:\\n{answer[:600]}\\n\\n\"\n"
    "        \"List the key factual claims in the answer (max 5). \"\n"
    "        \"For each claim state whether it can be inferred from the context. \"\n"
    "        'Return ONLY valid JSON: {\"claims\": [{\"claim\": \"...\", \"supported\": true}]}'\n"
    "    )\n"
    "    try:\n"
    "        resp = client.chat.completions.create(\n"
    "            model=\"gpt-4o-mini\",\n"
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n"
    "            temperature=0, max_tokens=300,\n"
    "        )\n"
    "        data = json.loads(resp.choices[0].message.content.strip())\n"
    "        claims = data.get(\"claims\", [])\n"
    "        if not claims:\n"
    "            return None\n"
    "        return round(sum(1 for c in claims if c.get(\"supported\")) / len(claims), 3)\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "def ragas_answer_correctness(question, answer, reference):\n"
    "    \"\"\"Answer Correctness (p.109): LLM judge 1-5, normalised to 0-1.\"\"\"\n"
    "    if not client or not answer:\n"
    "        return None\n"
    "    ref_text = reference[:400] if reference else \"(no reference)\"\n"
    "    prompt = (\n"
    "        f\"Question: {question}\\n\"\n"
    "        f\"Reference: {ref_text}\\n\"\n"
    "        f\"Answer: {answer[:600]}\\n\\n\"\n"
    "        \"Score the answer from 1 to 5 where:\\n\"\n"
    "        \"1 = incorrect or irrelevant\\n\"\n"
    "        \"3 = partially correct\\n\"\n"
    "        \"5 = fully correct and well-aligned with the reference\\n\"\n"
    "        'Return ONLY valid JSON: {\"score\": N}'\n"
    "    )\n"
    "    try:\n"
    "        resp = client.chat.completions.create(\n"
    "            model=\"gpt-4o-mini\",\n"
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n"
    "            temperature=0, max_tokens=20,\n"
    "        )\n"
    "        data = json.loads(resp.choices[0].message.content.strip())\n"
    "        return round(int(data.get(\"score\", 3)) / 5.0, 3)\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "# --- Evaluate LLM vs Agent on both benchmarks ----------------------------\n"
    "\n"
    "def eval_ragas(benchmark):\n"
    "    rows = []\n"
    "    for result in benchmark:\n"
    "        q         = result['question']\n"
    "        reference = ' '.join(result.get('expected_points', [])) or q\n"
    "        for stage in ['LLM', 'Agent']:\n"
    "            sd      = result['stages'].get(stage, {})\n"
    "            answer  = sd.get('answer', '')\n"
    "            context = sd.get('context', '')\n"
    "            rows.append({\n"
    "                'id':          result['id'],\n"
    "                'stage':       stage,\n"
    "                'sem_sim':     ragas_semantic_similarity(answer, reference),\n"
    "                'ans_rel':     ragas_answer_relevancy(q, answer),\n"
    "                'ctx_rel':     ragas_context_relevancy(q, context),\n"
    "                'faith':       ragas_faithfulness(answer, context),\n"
    "                'correctness': ragas_answer_correctness(q, answer, reference),\n"
    "            })\n"
    "    return rows\n"
    "\n"
    "print('Computing RAGAS metrics for Cyber benchmark  (LLM calls included)...')\n"
    "cyber_ragas = eval_ragas(cyber_benchmark)\n"
    "print('Computing RAGAS metrics for Faraday benchmark (LLM calls included)...')\n"
    "faraday_ragas = eval_ragas(faraday_benchmark)\n"
    "\n"
    "# --- Display table -------------------------------------------------------\n"
    "\n"
    "def show_ragas_table(label, rows):\n"
    "    fmt = lambda v: f'{v:.3f}' if v is not None else '  n/a'\n"
    "    print(f\"\\n{'─'*80}\")\n"
    "    print(f'  {label}  —  RAGAS Metrics (LLM vs Agent)')\n"
    "    print(f\"{'─'*80}\")\n"
    "    hdr = f\"{'ID':<13} {'Stage':<8} {'SemSim':>7} {'AnsRel':>7} {'CtxRel':>7} {'Faith':>7} {'Correct':>8}\"\n"
    "    print(hdr)\n"
    "    print('─' * len(hdr))\n"
    "    for r in rows:\n"
    "        print(f\"{r['id']:<13} {r['stage']:<8} {fmt(r['sem_sim']):>7} {fmt(r['ans_rel']):>7} \"\n"
    "              f\"{fmt(r['ctx_rel']):>7} {fmt(r['faith']):>7} {fmt(r['correctness']):>8}\")\n"
    "    print()\n"
    "    llm_rows = [r for r in rows if r['stage'] == 'LLM']\n"
    "    agt_rows = [r for r in rows if r['stage'] == 'Agent']\n"
    "    for metric in ['sem_sim', 'ans_rel', 'ctx_rel', 'faith', 'correctness']:\n"
    "        lv = [r[metric] for r in llm_rows if r[metric] is not None]\n"
    "        av = [r[metric] for r in agt_rows if r[metric] is not None]\n"
    "        if lv and av:\n"
    "            d = np.mean(av) - np.mean(lv)\n"
    "            print(f'  \\u0394 {metric:<12}: {d:+.3f}  '\n"
    "                  f'(LLM={np.mean(lv):.3f}  Agent={np.mean(av):.3f})')\n"
    "\n"
    "show_ragas_table('Cyber',   cyber_ragas)\n"
    "show_ragas_table('Faraday', faraday_ragas)\n"
)

MD_10_6 = (
    "### 10.6  LLM-as-a-Judge: Pairwise Comparison\n"
    "\n"
    "**LLM-as-a-Judge** (slide deck p.\u2009112) uses a capable LLM as an automated evaluator.  "
    "Here we apply the *pairwise comparison* variant: for each benchmark question the judge model "
    "(GPT-4o-mini) sees both the **LLM baseline** answer and the **Agent** answer side-by-side "
    "and decides which is better.\n"
    "\n"
    "This tests whether the agentic pipeline produces qualitatively superior answers \u2014 a "
    "complementary signal to the numerical RAGAS scores above.\n"
)

CODE_10_6 = (
    "# 10.6  LLM-as-a-Judge: Pairwise comparison (LLM baseline vs Agent)\n"
    "\n"
    "def llm_pairwise_judge(question, answer_a, answer_b):\n"
    "    \"\"\"LLM-as-a-Judge (p.112): pairwise comparison, returns winner A/B/tie + reason.\"\"\"\n"
    "    if not client:\n"
    "        return None\n"
    "    prompt = (\n"
    "        \"You are an impartial evaluator. Two systems answered the same question. \"\n"
    "        \"Decide which answer is better based on accuracy, completeness, and relevance.\\n\\n\"\n"
    "        f\"Question: {question}\\n\\n\"\n"
    "        f\"Answer A (LLM baseline):\\n{answer_a[:500]}\\n\\n\"\n"
    "        f\"Answer B (Agent):\\n{answer_b[:500]}\\n\\n\"\n"
    "        'Return ONLY valid JSON: '\n"
    "        '{\"winner\": \"A\" or \"B\" or \"tie\", \"reason\": \"one sentence\"}'\n"
    "    )\n"
    "    try:\n"
    "        resp = client.chat.completions.create(\n"
    "            model=\"gpt-4o-mini\",\n"
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n"
    "            temperature=0, max_tokens=120,\n"
    "        )\n"
    "        return json.loads(resp.choices[0].message.content.strip())\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "print('LLM-as-a-Judge \\u2014 Pairwise: LLM baseline vs Agent')\n"
    "print('=' * 70)\n"
    "\n"
    "for label, benchmark in [('Cyber', cyber_benchmark), ('Faraday', faraday_benchmark)]:\n"
    "    print(f'\\n{label} Benchmark')\n"
    "    print('-' * 50)\n"
    "    wins = {'A': 0, 'B': 0, 'tie': 0}\n"
    "    for result in benchmark:\n"
    "        q       = result['question']\n"
    "        llm_ans = result['stages']['LLM']['answer']\n"
    "        agt_ans = result['stages']['Agent']['answer']\n"
    "        verdict = llm_pairwise_judge(q, llm_ans, agt_ans)\n"
    "        if verdict:\n"
    "            w   = verdict.get('winner', '?')\n"
    "            wins[w] = wins.get(w, 0) + 1\n"
    "            tag = 'Agent wins' if w == 'B' else ('LLM wins' if w == 'A' else 'Tie')\n"
    "            print(f\"  {q[:55]:<55}  {tag}\")\n"
    "            print(f\"    {verdict.get('reason','')[:80]}\")\n"
    "    print(f\"\\n  Summary \\u2014 LLM wins: {wins.get('A',0)},  \"\n"
    "          f\"Agent wins: {wins.get('B',0)},  Tie: {wins.get('tie',0)}\")\n"
)


def make_md(src):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8],
            "metadata": {}, "source": src}

def make_code(src):
    return {"cell_type": "code", "id": uuid.uuid4().hex[:8],
            "metadata": {}, "source": src,
            "execution_count": None, "outputs": []}


with open(NOTEBOOK, encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']
# Verify targets
print("Before:")
for i in range(40, 44):
    print(f"  [{i}]", cells[i]['cell_type'], repr(''.join(cells[i]['source'])[:60]))

cells[40] = make_md(MD_10_5)
cells[41] = make_code(CODE_10_5)
cells[42] = make_md(MD_10_6)
cells[43] = make_code(CODE_10_6)

with open(NOTEBOOK, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("\nAfter:")
for i in range(40, 44):
    print(f"  [{i}]", cells[i]['cell_type'], repr(''.join(cells[i]['source'])[:60]))

print("\nDone. Cells 41-44 replaced with RAGAS-inspired metrics (pp. 103-112).")
