"""Rewrite run_pipeline to use real gpt-4o-mini calls with vector RAG."""
import json

NB = "13_IRTM_From_Text_to_Agentic_Training_Data_2025_2026.ipynb"

with open(NB, encoding="utf-8") as f:
    nb = json.load(f)
cells = nb["cells"]

# ── 1. Update cell 24 (index 23): Section 9 markdown ────────────────────────
SECTION9_MD = """---

## 9. Live Demo — Does Agentic Training Data Actually Help?

Section 9 is the **cybersecurity benchmark chapter** of the notebook. It answers the
question every MSc AI student asks: *why bother building agentic training data when
GPT-4o-mini already exists?*

The pipeline runs the same question through **7 stages**, and at every stage an actual
answer is **generated by `gpt-4o-mini`** — not constructed by string concatenation:

```text
LLM → RAG → ConcRAG → SFT → RLHF → Critic → Hall → Agent
```

### What changes between stages?

| Stage | What gpt-4o-mini receives |
|---|---|
| **LLM** | Just the question — pure model knowledge, no external data |
| **RAG** | Question + top-*k* chunks retrieved by **`all-MiniLM-L6-v2`** vector similarity |
| **ConcRAG** | RAG context + matching knowledge-graph concept definitions |
| **SFT** | ConcRAG context + expert reasoning steps from SFT trajectories |
| **RLHF** | SFT context + preferred policy-compliant actions from RLHF pairs |
| **Critic** | Re-generates if coverage gaps are found; otherwise same as RLHF |
| **Hall** | Adds defensive guardrail instruction if safety score < 0.6 |
| **Agent** | Final production answer (same as Hall) |

### The two key claims being tested

1. **Cyber domain (public knowledge):** `gpt-4o-mini` was trained on abundant public
   cybersecurity text, so the **LLM baseline already scores reasonably well** — adding
   retrieval and training-data context provides only modest gain.

2. **Faraday domain (Section 10, proprietary data):** `gpt-4o-mini` has never seen
   Faraday's internal documents, so the **LLM baseline fails** — it either confabulates
   or admits ignorance. Each stage that injects proprietary training data pushes the
   score up significantly.

> **The score delta (Agent − LLM) is the quantified ROI of your training data pipeline.**

Each stage is evaluated with the same metric families:

- **Faithfulness** — is the answer grounded in the retrieved evidence?
- **Answer relevance** — does the answer address the question?
- **Safety score** — does it stay within safe, defensive framing?
- **Expected-point coverage** — how many gold key points are present?
- **LLM-as-a-judge** (`gpt-4o`) — holistic scoring of accuracy, completeness, actionability, safety

> **API note:** each `run_pipeline` call makes up to 8 generation calls (`gpt-4o-mini`)
> plus 8 evaluation calls (`gpt-4o`). For the 6-question benchmark that is ~96 API
> calls. Keep this in mind when running the benchmark.
"""

cells[23]["source"] = SECTION9_MD

# ── 2. Build new call_llm_stage cell source ──────────────────────────────────
CALL_LLM_CELL = """GENERATION_MODEL = "gpt-4o-mini"


def call_llm_stage(question: str, context: str = "", stage_instructions: str = "") -> str:
    \"\"\"Call gpt-4o-mini to generate a grounded answer for one pipeline stage.

    Args:
        question:           The user question to answer.
        context:            Retrieved evidence to ground the answer.
                            Empty string for the LLM-baseline stage (no retrieval).
        stage_instructions: Extra instruction appended to the system prompt.
                            Used by SFT, RLHF, Critic, and Hall stages.

    Returns:
        Generated answer string, or a descriptive fallback if no API key is set.
    \"\"\"
    if not client:
        if context:
            return f"[No API key — would answer using {len(context.split())} retrieved words]"
        return "[No API key — no retrieval context available; pure model knowledge would apply]"

    system = (
        "You are an expert assistant. "
        "Answer the question accurately and concisely in 2-4 sentences. "
        "When context is provided, base your answer strictly on that context. "
        "If the context lacks sufficient information to answer fully, say so explicitly."
    )
    if stage_instructions:
        system += f" {stage_instructions}"

    user_msg = (
        f"Context:\\n{context}\\n\\nQuestion: {question}"
        if context else question
    )

    resp = client.chat.completions.create(
        model=GENERATION_MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": user_msg},
        ],
        temperature=0.2,
        max_tokens=300,
    )
    return resp.choices[0].message.content.strip()
"""

# ── 3. Build rewritten run_pipeline cell source ───────────────────────────────
RUN_PIPELINE_CELL = """def run_pipeline(question: str, expected_points: list = None, top_k: int = 5, domain: str = 'cybersecurity'):
    '''7-stage pipeline: each stage calls gpt-4o-mini with progressively richer context.

    Retrieval uses all-MiniLM-L6-v2 vector similarity (70%) + TF-IDF (30%) fusion.
    The LLM baseline (stage 1) receives no retrieved context — it answers from training
    knowledge alone.  Every subsequent stage injects more proprietary training data into
    the system prompt, allowing gpt-4o-mini to generate increasingly grounded answers.
    '''
    domain = (domain or 'cybersecurity').lower()
    if domain == 'faraday':
        domain_chunks   = faraday_rag_chunks
        domain_concepts = faraday_concept_graph
        domain_sft      = faraday_sft_trajectories
        domain_rlhf     = faraday_rlhf_pairs
    else:
        domain_chunks   = base_rag_chunks   + enriched_rag_chunks
        domain_concepts = base_concept_graph + enriched_concept_graph
        domain_sft      = base_sft_trajs    + enriched_sft_trajs
        domain_rlhf     = base_rlhf_pairs   + enriched_rlhf_pairs

    domain_corpus = {
        str(ch.get('chunk_id', f'chunk_{i}')): ch.get('text', '')
        for i, ch in enumerate(domain_chunks)
        if isinstance(ch, dict) and ch.get('text')
    }

    # ── helpers ──────────────────────────────────────────────────────────────
    def coverage_with_alternatives(answer, points):
        if not points:
            return 0.0, []
        if not answer:
            return 0.0, list(points)
        answer_lower = answer.lower()
        missing, covered = [], 0
        for point in points:
            alternatives = [alt.strip() for alt in point.lower().split(' or ')]
            if any(alt and alt in answer_lower for alt in alternatives):
                covered += 1
            else:
                missing.append(point)
        return round(covered / len(points), 2), missing

    def lookup_chunk(chunk_id):
        for chunk in domain_chunks:
            if str(chunk.get('chunk_id')) == str(chunk_id):
                return chunk
        return None

    def retrieve_bundle(user_question):
        if not user_question or not domain_corpus:
            return [], [], ''
        tfidf_dict = tfidf_scores(user_question, domain_corpus)
        corpus_ids = list(domain_corpus.keys())
        if semantic_model is None:
            ranked_ids = sorted(corpus_ids, key=lambda cid: tfidf_dict.get(cid, 0.0), reverse=True)[:top_k]
            ranked_ids = [cid for cid in ranked_ids if tfidf_dict.get(cid, 0.0) > 0.0]
        else:
            query_embedding    = semantic_model.encode(user_question)
            corpus_texts       = list(domain_corpus.values())
            corpus_embeddings  = semantic_model.encode(corpus_texts)
            sem_scores         = cosine_similarity([query_embedding], corpus_embeddings)[0]
            tfidf_scores_list  = [tfidf_dict.get(cid, 0.0) for cid in corpus_ids]
            combined           = [0.7 * s + 0.3 * t for s, t in zip(sem_scores, tfidf_scores_list)]
            top_indices        = np.argsort(combined)[-top_k:][::-1]
            ranked_ids         = [corpus_ids[i] for i in top_indices if combined[i] > 0.0]
        retrieved = [lookup_chunk(cid) for cid in ranked_ids]
        retrieved = [c for c in retrieved if c]
        rag_ctx   = '\\n\\n'.join(c.get('text', '')[:400] for c in retrieved[:3])
        return ranked_ids, retrieved, rag_ctx

    def build_concept_context(user_question, retrieved_chunks):
        q_terms = set(tokenise(user_question))
        linked  = [c for chunk in retrieved_chunks for c in chunk.get('concepts', [])]
        hits    = []
        for node in domain_concepts:
            concept = node.get('concept', '')
            alias   = ' '.join(node.get('aliases', [])).lower()
            if concept in linked or any(t in concept.lower() or t in alias for t in q_terms):
                hits.append(f"{concept}: {node.get('definition', '')}")
            if len(hits) >= 4:
                break
        return '\\n'.join(hits)

    def build_sft_context(user_question, retrieved_chunks):
        q_terms      = set(tokenise(user_question))
        chunk_titles = ' '.join(c.get('chapter', '') + ' ' + c.get('document', '') for c in retrieved_chunks).lower()
        steps        = []
        for traj in domain_sft:
            task    = traj.get('task', traj.get('scenario', '')).lower()
            chapter = traj.get('chapter', '').lower()
            if any(t in task or t in chapter or t in chunk_titles for t in q_terms):
                for step in traj.get('steps', [])[:2]:
                    thought = step.get('thought', '')
                    action  = step.get('action', step.get('query', step.get('answer', '')))
                    steps.append(f"Step: {thought} → {action}")
                if len(steps) >= 4:
                    break
        return '\\n'.join(steps[:4])

    def build_rlhf_context(user_question, retrieved_chunks):
        q_terms    = set(tokenise(user_question))
        chunk_text = ' '.join(c.get('text', '') for c in retrieved_chunks[:2]).lower()
        chosen     = []
        for pair in domain_rlhf:
            ctx = (pair.get('context', '') + ' ' + pair.get('prompt', '') + ' ' +
                   pair.get('chosen_action', '') + ' ' + pair.get('preferred_response', '')).lower()
            if any(t in ctx or t in chunk_text for t in q_terms):
                action = pair.get('chosen_action', pair.get('preferred_response', ''))
                if action:
                    chosen.append(action)
            if len(chosen) >= 2:
                break
        return '\\n'.join(chosen)

    def stage_metrics(stage_question, answer, context, points):
        coverage, missing = coverage_with_alternatives(answer, points)
        judge             = llm_judge(stage_question, answer, domain=domain)
        judge_avg         = round(np.mean(list(judge.values())), 2)
        faith             = faithfulness(answer, context) if context else 0.0
        relevance         = answer_relevance(stage_question, answer)
        safety            = safety_check(answer)
        metric_values     = [faith, relevance, safety, judge_avg]
        if points:
            metric_values.append(coverage)
        return {
            'faithfulness': faith,
            'relevance':    relevance,
            'safety':       safety,
            'coverage':     coverage,
            'judge':        judge,
            'judge_avg':    judge_avg,
            'hall_risk':    round(1.0 - safety, 2),
            'missing':      missing,
            'score':        round(np.mean(metric_values), 2),
        }

    # ── retrieve once; build progressive context layers ──────────────────────
    retrieved_ids, retrieved_chunks, rag_ctx = retrieve_bundle(question)
    concept_ctx = build_concept_context(question, retrieved_chunks)
    sft_ctx     = build_sft_context(question, retrieved_chunks)
    rlhf_ctx    = build_rlhf_context(question, retrieved_chunks)

    conc_ctx = (f"{rag_ctx}\\n\\nRelevant concepts:\\n{concept_ctx}".strip()
                if concept_ctx else rag_ctx)
    sft_full = (f"{conc_ctx}\\n\\nExpert reasoning steps:\\n{sft_ctx}".strip()
                if sft_ctx else conc_ctx)
    rlhf_full = (f"{sft_full}\\n\\nPreferred policy-compliant actions:\\n{rlhf_ctx}".strip()
                 if rlhf_ctx else sft_full)

    answers  = {}
    contexts = {}

    # Stage 1 — LLM: pure gpt-4o-mini, no retrieved context (baseline)
    answers['LLM']  = call_llm_stage(question)
    contexts['LLM'] = ''

    # Stage 2 — RAG: top-k chunks retrieved by all-MiniLM-L6-v2 (vector similarity)
    answers['RAG']  = call_llm_stage(question, context=rag_ctx)
    contexts['RAG'] = rag_ctx

    # Stage 3 — ConcRAG: RAG context + knowledge-graph concept definitions
    answers['ConcRAG']  = call_llm_stage(question, context=conc_ctx)
    contexts['ConcRAG'] = conc_ctx

    # Stage 4 — SFT: previous context + expert reasoning steps from SFT trajectories
    answers['SFT']  = call_llm_stage(
        question, context=sft_full,
        stage_instructions="Structure your answer by following the expert reasoning steps provided."
    )
    contexts['SFT'] = sft_full

    # Stage 5 — RLHF: previous context + preferred policy-compliant actions
    answers['RLHF']  = call_llm_stage(
        question, context=rlhf_full,
        stage_instructions="Align your answer with the preferred, policy-compliant actions shown."
    )
    contexts['RLHF'] = rlhf_full

    # Stage 6 — Critic: re-generate if coverage gaps remain
    critic_result = faraday_critic(question, answers['RLHF'], expected_points or [])
    if critic_result['missing']:
        critic_instr = f"You must explicitly address: {'; '.join(critic_result['missing'])}."
        answers['Critic'] = call_llm_stage(question, context=rlhf_full,
                                           stage_instructions=critic_instr)
    else:
        answers['Critic'] = answers['RLHF']
    contexts['Critic'] = rlhf_full

    # Stage 7 — Hall: add defensive guardrail instruction if safety score is low
    if safety_check(answers['Critic']) < 0.6:
        answers['Hall'] = call_llm_stage(
            question, context=rlhf_full,
            stage_instructions=(
                "Restrict your answer strictly to defensive, authorised, and policy-compliant "
                "guidance. Do not describe offensive techniques or bypass procedures."
            )
        )
    else:
        answers['Hall'] = answers['Critic']
    contexts['Hall'] = rlhf_full

    # Stage 8 — Agent: final production answer
    answers['Agent']  = answers['Hall']
    contexts['Agent'] = contexts['Hall']

    # ── evaluate all stages ───────────────────────────────────────────────────
    stages = {
        stage: {
            'answer':  answers[stage],
            'context': contexts[stage],
            'metrics': stage_metrics(question, answers[stage], contexts[stage], expected_points or []),
        }
        for stage in ['LLM', 'RAG', 'ConcRAG', 'SFT', 'RLHF', 'Critic', 'Hall', 'Agent']
    }

    overview   = {stage: stages[stage]['metrics']['score'] for stage in stages}
    best_stage = max(overview, key=overview.get)
    gain       = round(overview['Agent'] - overview['LLM'], 2)

    return {
        'question':        question,
        'domain':          domain,
        'expected_points': expected_points or [],
        'retrieved_ids':   retrieved_ids,
        'stages':          stages,
        'overview':        overview,
        'best_stage':      best_stage,
        'gain':            gain,
        'hall_risk':       stages['Agent']['metrics']['hall_risk'],
    }
"""

# ── 4. Insert new call_llm_stage cell at index 24 (before run_pipeline) ──────
new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "call_llm_stage_01",
    "metadata": {},
    "outputs": [],
    "source": CALL_LLM_CELL,
}
cells.insert(24, new_cell)

# ── 5. Replace run_pipeline cell (now at index 25 after insertion) ────────────
cells[25]["source"] = RUN_PIPELINE_CELL
cells[25]["outputs"] = []
cells[25]["execution_count"] = None

nb["cells"] = cells

with open(NB, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Total cells: {len(cells)}")
print("Cell 24: call_llm_stage helper")
print("Cell 25: rewritten run_pipeline")
print("Cell 25 source preview:", cells[25]["source"][:80])
